# Generated by Django 5.1.3 on 2024-11-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_game', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
