# Generated by Django 5.1.3 on 2024-11-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_game', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
