# Generated by Django 5.1.3 on 2024-11-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_game', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='highscore',
            name='day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='highscore',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
