# Generated by Django 5.1.3 on 2024-11-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_game', '0007_highscore_day_highscore_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='highscore',
            name='max_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='highscore',
            name='play_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
