# Generated by Django 5.1.3 on 2024-11-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_game', '0008_highscore_max_level_highscore_play_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highscore',
            name='max_level',
        ),
        migrations.RemoveField(
            model_name='highscore',
            name='play_time',
        ),
    ]
