# Generated by Django 5.1.3 on 2024-11-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_game', '0009_remove_highscore_max_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highscore',
            name='levels_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='highscore',
            name='total_play_time',
            field=models.IntegerField(default=0),
        ),
    ]
