# Generated by Django 5.1.3 on 2024-11-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_game', '0012_globalchatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalChatMessage',
        ),
    ]
