# Generated by Django 5.1.3 on 2024-11-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_game', '0014_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
