# Generated by Django 5.1.3 on 2024-11-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_game', '0017_gameroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameRoom',
        ),
    ]
