# Generated by Django 5.1.3 on 2024-11-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_game', '0018_delete_gameroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='avatar',
        ),
    ]
