# Generated by Django 5.1.3 on 2024-11-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_game', '0020_chatmessage_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars/'),
        ),
    ]
