# Generated by Django 5.1.3 on 2024-11-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_game', '0021_alter_chatmessage_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
