# Generated by Django 5.1.3 on 2024-11-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_game', '0023_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='highscore',
            name='levels_cleared',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='highscore',
            name='total_play_time',
            field=models.IntegerField(default=0),
        ),
    ]
