# Generated by Django 5.1.3 on 2024-11-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_game', '0024_highscore_levels_cleared_highscore_total_play_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highscore',
            name='levels_cleared',
        ),
        migrations.RemoveField(
            model_name='highscore',
            name='total_play_time',
        ),
    ]
